framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
