monolog:
    handlers:
        handlers:
            filter_for_errors:
                type: fingers_crossed
                action_level: error
                handler: file_handler

            file_handler:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"

            syslog_handler:
                type: syslog
                level: error
